* Земфира - гора
Zemfira-mountain

Медленно, медленно, медленно падает снег
Slowly, slowly, slowly falling snow

Ты видишь время, я вижу свет
You see, I see the light

Сзади подкрался на цыпочках кто-то чужой
Странное племя все тридцать лет

Врёте, вы всё врёте, и гора говорит: "Нет"
Врёте, вы всё врёте, и гора говорит: "Нет"

(You're fibbing, you keep on fibbing, and the mountian said no.).

Медленно, медленно, медленно падаю я
Ты видишь слёзы, я вижу дно
Мне рассказали, что в городе ходит печаль
Сеет вопросы, смотрит в окно

Врёте, вы всё врёте, и гора говорит: "Нет"
Врёте, вы всё врёте, и гора говорит: "Нет"

Нет
Нет
Нет

Гора говорит: "Нет"

Гора говорит: "Нет"

Гора говорит: "Нет"

У нас отрастали волосы, мы обрастали чувствами
Наевшись голоса, стали грустными
И день покатился, брошенный, жизнь покатилась в сторону
Устали бешено где-то поровну

Rear crept on tiptoe someone else's
Strange tribe all thirty years

Vrjote, you vrjote, and mountain said: "no"
Vrjote, you vrjote, and mountain said: "no"

Slowly, slowly, slowly I fall I
You see the tears I see bottom
I was told that the city walks of grief
Sows questions, looks out the window

Vrjote, you vrjote, and mountain said: "no"
Vrjote, you vrjote, and mountain said: "no"

No
No
No

Mountain said: "no"

Mountain said: "no"

Mountain said: "no"

We otrastali hair, we obrastali feelings
Voice, having become melancholy
And the day began to roll, the abandoned, life rolled aside
Tired furiously somewhere equally



* Название песни: СПИД
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 6
   Продолжительность звучания: 3 мин 33 сек

   Я сняла наyшники, слyшала ветеp.
   В откpытые двеpи пyстой маpшpyтки.
   Ветеp pассказал мне о стpашном секpете,
   Мол нам остаются последние сyтки.
   А y тебя СПИД, и значит мы yмpём.
   У тебя СПИД, и значит мы yмpём.
   Но y тебя СПИД, и значит мы yмpём.
   У тебя... и значит мы...
   Бyдем глотать в больнице лекаpства,
   Не дyмать пpо завтpа, не включать телевизоp,
   На каpте искать тpидесятое цаpство,
   А вдpyг повезёт, и достанyтся визы.
   Но y тебя СПИД, и значит мы yмpём.
   У тебя СПИД, и значит мы yмpём.
   А y тебя СПИД, и значит мы yмpём.
   А у тебя... и значит мы...
   Не pассчитались с долгами, свинтили.
   До скоpого, мама, ключи y соседки.
   Я дyла на веки пока не остыли,
   И плакали ивы, и ставили метки.
   А-а!
   Не видел ленивый в газете заметки, что
   А y тебя СПИД, и мы далеко.
   Но y тебя СПИД, и мы далеко,
   Но y тебя СПИД, и мы далеко,
   Но y тебя... и значит мы...

(Fairlyy sure spid is AIDS)
 
* Название песни: Созрела
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 3
   Продолжительность звучания: 3 мин 31 сек

   А девушка пьяна
   Уже который день,
   По уши влюблена
   В чужие прелести.
   Зеленая волна
   Накрыла ее тень,
   Размыла поцелуй,
   Что помнят челюсти.
   Кого-то ждет вокзал,
   Кого-то ждут домой.
   Ее никто не ждет,
   Не хочет ее тела.
   Ей проще не сказать,
   Ей проще быть немой,
   Когда она придет.
   А девушка созрела,
   А девушка созрела,
   А девушка созрела,
   Девушка...
   Ей радио-эфир
   Приветы передал
   Заказанные ею
   Самою же себе.
   Засмотреный до дыр
   С картинками журнал.
   В пустой квартире млеет,
   Саму себя любя.
   Кого-то ждет вокзал,
   Кого-то ждут домой.
   Ее никто не ждет,
   Не хочет ее тела.
   Ей проще не сказать,
   Ей проще быть немой,
   Когда она придет.
   А девушка созрела.


* Название песни: Прости меня, моя любовь (Forgive me, my love)
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 10
   Продолжительность звучания: 3 мин 36 сек

   Море обнимет, закопает в пески,
   Закинут рыболовы лески,
   Поймают в сети наши души,
   Прости меня, моя любовь.
   Поздно о чем-то думать, слишком поздно.
   Тебе, я чую, нужен воздух.
   Лежим в такой огромной луже,
   Прости меня, моя любовь.
   Джинсы воды набрали и прилипли.
   Мне кажется мы крепко влипли,
   Мне кажется потухло солнце,
   Прости меня, моя любовь.
   Тихо, не слышно ни часов ни чаек.
   Послушно сердце выключаем.
   И ты в песке, как будто в бронзе,
   Прости меня, моя любовь.

ENG: 
Sea
Will embrace
Fishers will cast their threads
And catch our souls into their nets

Forgive me my love

Late
To think of anything
It's too late
I feel you need air
We lie in this enormous puddle

Forgive me my love

Jeans
Gathered in water
And clung
I think we are caught firmly in it


*  Название песни: Трафик
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 2
   Продолжительность звучания: 4 мин 01 сек

   Кто придумал, скажи, эти пробки?
   В переулках зима
   Затаилась и ждет, что же будет.
   Мы с тобою в железной коробке.
   Ты давно не любовь,
   Просто чем-то похожие люди.
   Я чувствую, как звенят твои нервы.
   Шестера не выдержит, дернет первой.
   Мне в форточку дунет холодный ветер,
   Волна зашипит и испортит песню.
   Ты мне предложишь быть снова вместе,
   Я промолчу исподлобья робко.
   Все возможно могло быть иначе,
   Если б не эти ужасные пробки.
   Кто-то меряет время часами,
   А я живу от зимы до зимы,
   Мы с ней видишь ли, тезки.
   Я питаю себя чудесами,
   Но ты же все понимаешь,
   Ровно три перекрестка.
   Я чувствую, как звенят твои нервы,
   Шестера не выдержит, дернет первой.
   Мне в форточку дунет холодный ветер,
   Волна зашипит и испортит песню.
   Ты мне предложишь быть снова вместе,
   Я промолчу исподлобья робко.
   Все возможно могло быть иначе,
   Если б не эти ужасные пробки.


* Название песни: Знак бесконечность
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 3
   Продолжительность звучания: 5 мин 04 сек

   Я хочу, чтобы во рту оставался честный вкус сигарет,
   Мне очень дорог твой взгляд, мне крайне важен твой цвет,
   Я умираю, когда вижу то, что вижу и некому спеть,
   Я так боюсь не успеть, хотя бы что-то успеть.
   Замороженными пальцами в отсутствие горячей воды,
   Заторможенными мыслями в отсутствии конечно тебя.
   И я застыну, выстрелю в спину, выберу мину и добрый вечер!
   Я не нарочно, просто совпало, я разгадала знак бесконечность.
   Разочарованные фильмом, очарованные небом глаза.
   Я не смогу объяснить, но возвращаюсь назад.
   Проводи меня, останется не больше, но и не меньше чем звук,
   А звук всё тот же, что нить, но я по прежнему друг.
   Замороженными пальцами в отсутствие горячей воды,
   Заторможенными мыслями в отсутствии конечно тебя
   И я застыну, выстрелю в спину, выберу мину и добрый вечер!
   Я не нарочно, просто совпало, я разгадала знак бесконечность.
   И я застыну, выпрямлю спину, кепки надвину, и добрый вечер!
   Я не нарочно, просто совпало, я разгадала знак бесконечность.
   И я застыну, кепки надвину, что-то задвину, и добрый вечер!
   Я не нарочно, просто совпало, я разгадала знак бесконечность.

 
*   Название песни: Небомореоблака
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 1
   Продолжительность звучания: 3 мин 38 сек

   Эти серые лица не внушают доверия,
   Теперь я знаю, кому поёт певица Валерия.
   Я готова на многое, готова даже исправиться,
   Упакуйте, отдайте меня стюардессам-красавицам.
   Здравствуй небо, море, облака...
   Здравствуй небо, море, облака...
   Эти фильмы глупы, эти песни скучны и прилизаны,
   Мои мама и папа превратились давно в телевизоры.
   Я готова меняться не глядя с любым дозвонившимся,
   Посидим, поболтаем, покурим и, может быть, спишемся.
   Здравствуй небо, море, облака...
   Здравствуй небо, море, облака...
   Этот город заполнен деньгами и проститутками,
   Я не против ни тех, ни других, но только не сутками.
   Я готова забыть и начать, разумеется, заново,
   Приготовьте согласно условиям синего самого...
   Небо, море, облака...
   Здравствуй небо, море, облака...


*   Название песни: Повесица
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 12
   Продолжительность звучания: 3 мин 48 сек

   Раненое сердце весит тяжелее
   Пробую согреться, пью и не пьянею.
   Я прошу - верни меня.
   Кто тебе позволит или не позволит
   Чего же ты боишься, Бога или боли
   Я прощу. Верни меня...
   Я хочу повеситься
   Фонарь, веревка, лестница. Забыть...
   Два кровавых месяца
   Столько мин и пострадавших
   Буду висеть, молчать и любить
   С кем-то говорю и ничего не слышу
   Углы твои горю, люблю и ненавижу
   Я прошу - верни меня.
   Мимо проплывают люди и недели
   И я неплохо к вам, но вы мне надоели
   Я прощу. Верни меня...
   Я хочу повеситься
   Фонарь, веревка, лестница. Забыть...
   Два кровавых месяца
   Столько мин и пострадавших
   Буду висеть, молчать и любить
   Я хочу повеситься
   Я хочу повеситься
   Луна, улыбка, лестница. Забыть...
   Два кровавых месяца
   Столько мин и пострадавших
   Буду висеть, молчать и любить


*   Название песни: -140
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 11
   Продолжительность звучания: 3 мин 50 сек

   Cтpанно - тpамваи не ходят кpyгами,
   А только от кpая до кpая.
   Еще молодая весна пытает.
   Мимо созвездий запpyженных yлиц.
   Hам пеpвые кpылья веpнyлись,
   Еще не пpоснyлись, а все тyда же.
   А в забытом тобою отpезке,
   Мне все было ново и все интеpесно.
   И на забытой тобою фотке минyс сто соpок
   И вечное лето.
   А в забытом тобою отpезке,
   Мне все было ново и все интеpесно.
   И на забытой тобою фотке минyс сто соpок,
   Ужас.
   Помнишь? Да нет, ни фига ты не помнишь.
   А мне же не очень-то нyжно.
   И только сопливо и голос пpостyжен.
   Где-то ведь ходят по кpyгy тpамваи,
   И мчатся созpевшие стаи,
   И кpyтят мои винилы подpостки.
   А в забытом тобою отpезке,
   Мне все было ново и все интеpесно.
   И на забытой тобою фотке минyс сто соpок
   И вечное лето.
   А в забытом тобою отpезке,
   Мне все было ново и все интеpесно.
   И на забытой тобою фотке минyс сто соpок,
   Ужас.


*   Название песни: 1000 лет (quot;Тысяча летquot;)
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Спасибо" (2007), трек 10
   Продолжительность звучания: 4 мин 10 сек

   Первый день ноября
   Замерзают края
   И горят фонари
   Зря
   Проплыла над двором
   Стая синих ворон
   Колокольный в ушах
   Звон
   Бери "шанель"
   Пошли домой
   Облупилась зима
   Наступила зима
   И немного себя
   Жаль
   Ровно тысячу лет
   Я иду по земле
   Оставляя тебе
   След
   Бери "Шанель"
   Пошли домой

*   Название песни: Jim Beam (Уфа'97)
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 15
   Продолжительность звучания: 2 мин 24 сек

   По высоким по стаканам Jim Beam в губы
   Целоваться неприятно - герпес достал
   А под звёздами на крыше тепло вполне
   Может, сходим, погуляем, шагнём вперед
   А по... Господи, неважно, пластмассовые pучки...
   Ой, неинтересно, он менять ошибки сможет,
   Как и многое другое...
   Ровно двадцать лет я изучала эти штучки,
   Точно знаю - не поможет и с ума совсем не сводит... но...
   По высоким по стаканам Jim Beam в губы
   Целоваться непpиятно - геpпес достал
   А под звёздами на кpыше тепло вполне
   Может, сходим, погуляем, шагнём впеpёд
   А по... по необыкновению ищу на небе тучки,
   Hи одной пока не вижу этой ..... соседки,
   Меланхолик-алкоголик...
   Задом заноси ко мне пластмассовые pучки,
   Эй спасибо, что не вижу - довели меня до колик...
   Эй спасибо...
   Hаpкоман и меланхолик-алкоголик
   Да довели меня...
   Hаpкоман и меланхолик-алкоголик, алкоголик...
   Точки, стpочки, шепчет мимо...
   Точки, стpочки, шепчет мимо...
   По высоким по стаканам Jim Beam в губы
   Целоваться непpиятно - геpпес достал
   А под звёздами на кpыше тепло вполне
   Может, сходим, погуляем, шагнём впеpёд


*   Название песни: Juicy Fruit
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   Ходишь-гуляешь,
   Знаю, страдаешь.
   Было прохладно,
   Стало забавно.
   Juicy Fruit, Juicy Fruit,
   Juicy Fruit, люди врут.
   Про меня им не верь,
   Ведь у нас есть Juicy Fruit.
   Не говорила,
   Что крышу сносило.
   Не целовались,
   Вместе боялись.
   Juicy Fruit, Juicy Fruit,
   Люди врут, люди врут.
   Про меня им не верь,
   Ведь у нас есть Juicy Fruit.
   Всё так печально,
   Всё так нечаянно.
   Что же нам делать?
   Разве что смело
   Жевать Juicy Fruit, Juicy Fruit,
   Juicy Fruit, люди врут.
   Про меня им не верь,
   Ведь у нас есть Juicy Fruit.

*    Название песни: Not Alone
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   You, you going on,
   You brake my own.
   I'm ready some,
   And only you
   Can be my chance forever
   And think together.
   You, you going on,
   You brake my own.
   I'm glad is some,
   And only you
   Can be my chance forever
   And think together.


*   Название песни: Webgirl
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 10
   Продолжительность звучания: 4 мин 14 сек

   Девочка, живущая в сети,
   Нашедшая любовь между строк,
   Между небом и землей.
   Пальцами пытаясь угадать,
   Надеясь угадать до конца,
   До конца.
   Девочка, живущая в сети,
   Живущая за всех, до конца,
   На последнем этаже.
   Клавиши, хранящие тепло,
   Таящие вопрос никому,
   Никому.
   Может быть на том конце встретит
   В чьем-нибудь чужом лице третьем,
   Что-нибудь отдашь сердце,
   Кто-нибудь отдаст сердце и,
   Знаешь ли, бывет же чудо,
   Знаешь ли, встречают же люди,
   Может быть, и ты тоже...
   Может быть...
   Девочка, живущая в сети,
   Забывшая любовь между строк,
   Между небом и землей.
   Девочка, уставшие глаза,
   Догнавшие рассвет, только ей,
   Только ей.
   Девочка, живущая в сети...

*   Название песни: Zero
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 2
   Продолжительность звучания: 2 мин 47 сек

   Ла-ла-ла-ла-ла-лай...
   Ла-ла-ла-ла-ла-лай...
   Ла-ла-ла-ла-ла-ла-а-ай...
   Делай со мной что хочешь,
   Стань моей тенью внезапно,
   Ломай мои пальцы, целуй мою кожу,
   Так тянет расстаться, но мы же похожи.
   Ах, в твоих же зрачочках страх,
   И в них же чужая боль,
   Девять-ноль.
   Ла-ла-ла-ла-ла-лай...
   Ла-ла-ла-ла-ла-лай...
   Ла-ла-ла-ла-ла-ла-а-ай...
   Думай, но только ночью.
   Ты знаешь, я исчезаю внезапно.
   Сорви мои чувства, храни как гербарий.
   На слабости мускул себя разбазарив.
   Ах, в твоих же зрачочках страх,
   И в них же чужая боль,
   Девять-ноль.

*   Название песни: Ариведерчи
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 12
   Продолжительность звучания: 2 мин 46 сек

   Воpоны-москвички меня pазбyдили,
   Пpомокшие спички надеждy yбили
   Кypить: значит бyдy
   Дольше жить, значит бyдем...
   Коpабли в моей гавани жечь,
   Hа pyбли поменяю билет,
   Отpастить бы до самых до плеч
   Я никогда не веpнyсь
   Домой.
   C тобой мне так интеpесно, а с ними не очень.
   Я вижy что тесно, я помню что пpочно
   Даpю. Вpемя, видишь
   Я гоpю, кто-то спyтал
   И поджег меня. Аpиведеpчи.
   Hе yчили в глазок посмотpеть...
   И едва ли yспеют по плечи...
   Я pазобью тypникет,
   И побегy по своим...
   Обpатный change на билет,
   Я бyдy ждать ты звони,
   Мои обычные в шесть.
   Я стала стаpше на жизнь,
   Hавеpное нyжно yчесть...
   Коpабли в моей гавани.
   Hе взлетим так поплаваем
   Cтpелки pовно на два часа
   Hазад...
   В моей гавани.
   Hе взлетим так поплаваем.
   Cтpелки pовно на два часа.
   Hазад...
   Корабли в моей гавани.
   Hе взлетим так поплаваем.
   Cтpелки pовно на два часа.
   Hазад...

*   Название песни: Блюз
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 7
   Продолжительность звучания: 3 мин 29 сек

   Покатаемся по городу
   Отвези меня пожалуйста
   К мосту ближе, ближе. Здесь я дышу...
   От луны такие грустные
   До неё подпрыгнуть хочется
   Давай выпьем прямо здесь и сейчас
   И меня моя милиция
   Заберёт и не подавится
   Смотри, дальше, дальше. Здесь никогда...
   Покатаемся по городу
   Отвези меня пожалуйстя
   К мосту ближе, ближе. Здесь я дышу...


*   Название песни: Дыши
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 2
   Продолжительность звучания: 4 мин 10 сек

   Ты говоришь, что страшно я смеюсь
   Есть у меня один секрет
   Ты говоришь, что любишь. Я боюсь
   И так уже много тысяч лет.
   И не держи, мне известны все твои уловки
   Я только злюсь
   Дыши, ненавижу эти остановки
   Я, я всё равно вернусь.
   Вернусь... Вернусь...
   Я говорю об этом. Ты молчишь
   И не пытаешься понять.
   Я пропадаю где-то. Ты не спишь
   Твой аналитик - просто блядь.
   И не держи, мне известны все твои уловки
   Я только злюсь
   Дыши, ненавижу эти остановки
   Я, я всё равно вернусь.
   Вернусь... Вернусь...

*   Название песни: Ждать
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   Хали-гали дождик,
   Хали-гали хлещет.
   Видишь-слышишь дождик
   Обнимает плечи.
   Плачем я и небо,
   Ты же уезжаешь
   В теплые наверно
   Хали-гали.
   Мы будем ждать,
   Я и твой город
   Будем ждать.
   Медленно скоро.
   На перронах,
   На аэродромах,
   На остановках,
   И даже дома.
   Хали-гали тучки,
   Хали-гали в танце
   Заболели тучки
   И давай влюбляться.
   Я же это дело
   С крыши углядела,
   Просто обалдела
   Хали-гали.
   Мы будем ждать,
   Я и твой город
   Будем ждать.
   Медленно скоро.
   На перронах,
   На аэродромах,
   На остановках,
   И даже дома.

*   Название песни: Жужа
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 10
   Продолжительность звучания: 4 мин 52 сек

   Я ничего не хочу, жужа
   Я словно высохшая лужа
   И в моём сердце совсем пусто
   И холодно
   И заводские дымят трубы
   И ты целуешь меня в губы
   И обещали дожди с юга
   Но где они.
   Сегодня пьяный опять вечер
   Но так мне кажется чуть легче
   И даже звёзды горят ярче
   Романтика
   Мы растворяем друг-друга, жужа
   Как кислота или что хуже
   И нам нести эту боль вместе
   Стеклянную
   И по реке всё плывут баржи
   Они намного меня старше
   Но всё равно приплывёт каждый
   Куда-нибудь
   Куда-нибудь...
   Куда-нибудь...

*   Название песни: Земфира
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 14
   Продолжительность звучания: 3 мин 58 сек

   Hе бери себе в голову, Земфира, не бери,
   Прогоняй ностальгию мимо дымом в потолок,
   И не трогай телефон и заусенца,
   Ты же можешь, я-то знаю...
   Кроме счастья есть зима, простуды,
   Просто невезенье, в воcкресенье,
   Ты же будешь улыбаться,
   И казаться, между прочим, лучше всех...
   Убивай свою прихоть, сколько можешь, убивай,
   Расскажи как хотелось: грелась тысяче зеркал.
   И не надо никого и даже мыслей, -
   Так спокойней, я-то знаю...
   Кроме счастья есть зима, простуды,
   Просто невезенье, в воcкресенье,
   Ты же будешь улыбаться,
   И казаться, между прочим, лучше всех...
   Объясни себе важное, пусть долго - объясни,
   Разозлись, если хочешь, можешь в высь, и разозлись.
   Выбирай себе же сны и настроенья
   Впечaтлений, я-то знаю...
   Кроме счастья есть зима, простуды,
   Просто невезенье, в воcкресенье,
   Ты же будешь улыбаться,
   И казаться, между прочим, лучше всех...
   Hе бери себе в голову, Земфира, не бери,
   Прогоняй ностальгию мимо дымом в потолок,
   И не трогай телефон и заусенца,
   Ты же можешь, я-то знаю...


*   Название песни: Знак бесконечность
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 3
   Продолжительность звучания: 5 мин 04 сек

   Я хочу, чтобы во рту оставался честный вкус сигарет,
   Мне очень дорог твой взгляд, мне крайне важен твой цвет,
   Я умираю, когда вижу то, что вижу и некому спеть,
   Я так боюсь не успеть, хотя бы что-то успеть.
   Замороженными пальцами в отсутствие горячей воды,
   Заторможенными мыслями в отсутствии конечно тебя.
   И я застыну, выстрелю в спину, выберу мину и добрый вечер!
   Я не нарочно, просто совпало, я разгадала знак бесконечность.
   Разочарованные фильмом, очарованные небом глаза.
   Я не смогу объяснить, но возвращаюсь назад.
   Проводи меня, останется не больше, но и не меньше чем звук,
   А звук всё тот же, что нить, но я по прежнему друг.
   Замороженными пальцами в отсутствие горячей воды,
   Заторможенными мыслями в отсутствии конечно тебя
   И я застыну, выстрелю в спину, выберу мину и добрый вечер!
   Я не нарочно, просто совпало, я разгадала знак бесконечность.
   И я застыну, выпрямлю спину, кепки надвину, и добрый вечер!
   Я не нарочно, просто совпало, я разгадала знак бесконечность.
   И я застыну, кепки надвину, что-то задвину, и добрый вечер!
   Я не нарочно, просто совпало, я разгадала знак бесконечность.


*   Название песни: Искала
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 11
   Продолжительность звучания: 3 мин 30 сек

   Я искала тебя годами долгими,
   Искала тебя дворами темными.
   В журналах, в кино, среди друзей.
   В день, когда нашла, с ума сошла.
   Ты, совсем как во сне,
   Совсем как в альбомах,
   Где я рисовала тебя гуашью.
   Дальше были звонки, ночные больше.
   Слезы, нервы, любовь и стрелки в Польше.
   Дети, но не мои, старые зазнобы,
   Куришь каждые пять, мы устали оба.
   Ты, совсем как во сне,
   Совсем как в альбомах,
   Где я рисовала тебя гуашью.
   ...годами долгими.
   ...ночами тёмными.
   ...годами долгими.
   Ты, совсем как во сне,
   Совсем как в альбомах,
   Где я рисовала тебя гуашью.
   Я искала тебя годами долгими,
   Искала тебя дворами тёмными,
   В журналах, в кино, годами долгими,
   Искала тебя ночами, чами, чами, чами...


*   Название песни: Итоги
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 3
   Продолжительность звучания: 3 мин 18 сек

   Я ухожу оставляя горы окурков
   Километры дней, миллионы придурков
   Литры крови подаренной или потерянной.
   Оставляю друзей, тех что наполовину
   Себя на радиоволнах, коротких и длинных
   Осчастливленных мною и обиженных мною.
   Терзает ночь мои опухшие лики
   Я ничего, ничего об этом не помню
   Моя любовь осталась в двадцатом веке
   И снова ночь. Стрела отравлена ядом
   Я никогда, никогда тебя не оставлю
   Ты полежи со мною неслышно рядом.
   Я ухожу оставляя причины для споров
   Мою смешную собаку, мой любимый город
   Недокуренный план, гигабайт фотографий.
   Оставляю мечту, может кто-то захочет
   Три тетради сомнений моим неровным почерком
   Деньги в банке и многих себе подобных.
   Терзает ночь мои опухшие лики
   Я ничего, ничего об этом не помню
   Моя любовь осталась в двадцатом веке
   Ночь. Стрела отравлена ядом
   Я никогда, никогда тебя не оставлю
   Ты полежи со мною неслышно рядом.

*   Название песни: Каждую ночь
   Автор слов: Виктор Цой
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   Третий день с неба течет вода,
   Очень много течет воды.
   Говорят, так должно быть здесь,
   Говорят, это так всегда.
   Знаешь, каждую ночь
   Я вижу во сне море.
   Знаешь, каждую ночь
   Я слышу во сне песню.
   Знаешь, каждую ночь
   Я вижу во сне берег.
   Знаешь, каждую ночь...
   Мы приходим домой к себе,
   Люди ходят из дома в дом,
   Мы сидим у окна вдвоем,
   Хочешь, я расскажу тебе...
   Знаешь, каждую ночь
   Я вижу во сне море.
   Знаешь, каждую ночь
   Я слышу во сне песню.
   Знаешь, каждую ночь
   Я вижу во сне берег.
   Знаешь, каждую ночь...


*   Название песни: Снег начнётся
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Спасибо" (2007), трек 9
   Продолжительность звучания: 4 мин 25 сек

   Я вижу тебя
   Слышу тебя
   Бежишь ко мне по крышам
   Боишься опоздать
   В полнеба глаза
   Полжизни назад
   Отдай мне свое сердце
   Садись и будем ждать
   Когда снег начнется
   Снег начнется
   Я вижу тебя
   Слышу тебя
   Скажи мне свои тайны
   И где тебя искать
   Если снег начнется
   Снег начнется
   Я вижу тебя.


*   Название песни: Красота
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 13
   Продолжительность звучания: 3 мин 11 сек

   Какая красота,
   Дождь идет
   Я одна, на тротуарах пузыри
   Я считаю их
   Я не знаю Вас больше...


*   Название песни: Кто?
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 9
   Продолжительность звучания: 2 мин 52 сек

   В руки твои умру, в руки твои опять
   Не долетевший Икар.
   Да, не хватило сил, да, не туда просила,
   Что-нибудь, кроме гитар.
   Кто показал тебе звезды утром?
   Кто научил тебя видеть ночью?
   Кто, если не я?
   Я, я всегда буду за тобой.
   Я, я всегда буду за тебя.
   Нет, не отпущу.
   Десять минут любви, десять минут тепла,
   Вот и какой-то пустяк.
   Били по тормозам, я по твоим глазам
   Видела, что-то не так.
   Кто показал тебе звезды утром?
   Кто научил тебя видеть ночью?
   Кто, если не я?
   Я, я всегда буду за тобой.
   Я, я всегда буду за тебя.
   Нет, не отпущу.
   Сколько уже прошло, сколько еще пройдет,
   Мне без тебя тяжело.
   Просто давай дружить, в губы давай дружить,
   Я буду твоим НЛО.
   Кто показал тебе звезды утром?
   Кто научил тебя видеть ночью?
   Кто, если не я?
   Я, я всегда буду за тобой.
   Я, я всегда буду за тебя.
   Нет, не отпущу.
   Кто...
   Кто...
   Кто, если не я?
   Я, я всегда буду за тобой.
   Я, я всегда буду за тебя.
   Нет, не отпущу.

*   Название песни: Кукушка
   Автор слов: Виктор Цой
   Альбом: [20]"До свидания", сингл (2000)

   Песен еще ненаписанных, сколько?
   Скажи, кукушка, пропой.
   В городе мне жить или на выселках,
   Камнем лежать или гореть звездой, звездой.
   Солнце мое - взгляни на меня,
   Моя ладонь превратилась в кулак,
   И если есть порох - дай огня.
   Вот так...
   Кто пойдет по следу одинокому?
   Сильные да смелые
   Головы сложили в поле в бою.
   Мало кто остался в светлой памяти,
   В трезвом уме да с твердой рукой в строю, в строю.
   Солнце мое - взгляни на меня,
   Моя ладонь превратилась в кулак,
   И если есть порох - дай огня.
   Вот так...
   Где же ты теперь, воля вольная? С кем же ты сейчас
   Ласковый рассвет встречаешь? Ответь.
   Хорошо с тобой, да плохо без тебя,
   Голову да плечи терпеливые под плеть, под плеть.
   Солнце мое - взгляни на меня,
   Моя ладонь превратилась в кулак,
   И если есть порох - дай огня.
   Вот так...

*   Название песни: Sorry
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   Sorry


*   Название песни: Маечки
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 5
   Продолжительность звучания: 3 мин 10 сек

   Ты белый и светлый,
   Я - я тёмная, тёплая.
   Ты плачешь - не видит никто,
   А я - я комкаю стёкла, дypа.
   Ты так откpовенно любишь,
   Я, я так безнадёжно попала.
   Мы, мы шепчем дpyг дpyгy секpеты,
   Мы всё понимаем, и только этого мало.
   Анечка-а пpосила снять маечки,
   Анечка-а...
   Анечка-а пpосила снять маечки,
   Анечка-а...
   Ты стоишь своих откpовений,
   Я - я веpю, что тоже стою.
   Ты гений, я тоже гений,
   И если ты ищешь, значит нас двое.
   Больно бывает не только от боли.
   Стpашно бывает не только за совесть.
   Cтpанно, опять не хватило воли.
   Я множy окypки, ты пишешь повесть.
   Анечка-а пpосила снять маечки,
   Анечка-а...
   Анечка-а пpосила снять маечки,
   Анечка-а...

*   Название песни: Малыш
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 11
   Продолжительность звучания: 2 мин 50 сек

   Моё сознание несётся
   Ракетой в сторону солнца
   Меня не стоит бояться
   В меня не стоит влюбляться
   Ты очень милый парень,
   Но таких как я больше нету
   Давай договоримся -
   Будь со мной
   Смотри, я тебе покажу чудеса
   Лети...
   И мы потечём как реки
   В неоновые аптеки
   В известных всем переходах
   Стоят наши ледоходы
   Твоя ещё детская кожа
   Юные крепкие вены
   Успех наших начинаний, такая безумная пара
   Будь со мной
   Смотри, я тебе покажу чудеса
   Лети...
   Малыш,
   Смотри, я тебе подарю чудеса
   Лети...


*   Название песни: Мальчик
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Спасибо" (2007), трек 5
   Продолжительность звучания: 3 мин 47 сек

   Мальчик бежит по дороге
   Сшибая столбы
   Непослушные ноги
   Ему говорят
   Мы тебя приведем
   Но ни шагу назад
   Мальчик
   Желает быть богом
   Но это так трудно и грустно
   И так одиноко
   Он мне говорил это пьяный
   Глядя в глаза
   Денег - ноль
   Секса - ноль
   Музыка сдохла
   Мальчик - ноль
   Денег - ноль
   Секса - ноль
   Музыка сдохла
   Мальчик забыл по дороге
   Зачем он бежал
   Но бежал
   Возмужал
   А еще отрастил себе жало
   И стало бежать тяжелей
   Мимо дождей
   Фонарей
   Мимо снов и бессоннниц
   Быстрее
   Чтобы не опоздать и запомниться
   Жадно глотая улыбки людей
   Денег - ноль
   Секса - ноль
   Музыка сдохла
   Мальчик - ноль
   Денег - ноль
   Секса - ноль
   Музыка сдохла
   Музыка сдохла
   Денег - ноль
   Секса - ноль
   Музыка сдохла
   Мальчик - ноль
   Денег - ноль
   Секса - ноль
   Музыка сдохла
   Денег!..
   Мальчик - ноль.

*   Название песни: Мачо
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 4
   Продолжительность звучания: 4 мин 21 сек

   Позвони, и я буду ждать,
   Я буду знать, кому из нас верить.
   Расскажи, куда идти,
   Зачем идти, если заперты двери.
   Пьяный мачо лечит меня и плачет
   От того, что знает, как хорошо бывает.
   А - а - а - а.
   Проводи, и я буду плыть,
   Я буду стыть под слишком шумные воды.
   Перестань, твои глаза - мои глаза,
   В них просто разные коды.
   Пьяный мачо лечит меня и плачет
   От того, что знает, как хорошо бывает.
   А - а - а - а.
   Полюби, и мне осталось жить
   Ровно девять лун, а после вечное солнце.
   Проводи, и я буду плыть,
   Если хватит крон и если память вернется.

*   Название песни: Мечтой
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 13
   Продолжительность звучания: 3 мин 54 сек

   Её звали мечтой,
   Он хотел убежать,
   Да не сумел.
   И звонили звонки
   Через все позвонки,
   Да так он хотел
   Да
   Да я читала
   Да он хотел убежать
   Да, блин, не сумел
   Её звали мечтой
   Её звали мечтой
   Да так он хотел
   Да я читала ни о чём
   Да, да, да, да...
   Её звали мечтой
   Её звали мечтой
   Мечтой мечтой мечтой мечтой...

*   Название песни: Мы разбиваемся
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Спасибо" (2007), трек 4
   Продолжительность звучания: 3 мин 22 сек

   Мы разбегаемся
   По делам
   Земля разбивается
   Пополам
   Сотри меня
   Смотри в меня
   Останься
   Прости меня за слабость
   И за то что я
   Так странно и отчаянно
   Люблю
   Вздох сожаления
   На губах
   Зависли в неправильных
   Городах
   Звонки телефонные
   Под луной
   Границы условные
   Я с тобой
   Сотри меня
   Смотри в меня
   Останься
   Прости меня за слабость
   И за то что я
   Так странно и отчаянно
   Люблю
   Мы разбегаемся
   По делам
   Земля разбивается
   Пополам
   Вздох сожаления на губах
   Зависли в неправильных
   Городах
   Звонки телефонные
   Под луной
   Границы условные
   Я с тобой
   Мы разбегаемся
   По делам
   Земля разбивается

*   Название песни: Не отпускай
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 12
   Продолжительность звучания: 4 мин 05 сек

   Над моей пропастью
   У самой лопасти
   Кружатся глобусы,
   Старые фокусы.
   Я же расплакалась,
   Я не железная.
   Мама Америка,
   В двадцать два берега.
   Ты не отпускай меня,
   Не отпускай,
   Не отпускай меня,
   Вдруг кто увидит...
   Не отпускай меня,
   Не отпускай,
   Не отпускай меня,
   Вдруг кто увидит.
   Вечная юная.
   Сразу за дюнами
   Ждет тебя парусник
   Мною придуманный.
   Двадцать два месяца
   Глобусы бесятся,
   Люди прощаются,
   Но не возвращаются.
   Ты не отпускай меня,
   Не отпускай,
   Не отпускай меня,
   Вдруг кто увидит...
   Не отпускай меня,
   Не отпускай,
   Не отпускай меня,
   Вдруг кто увидит...
   Голуби прячутся,
   В небо не хочется.
   В списке не значится,
   И значит не молится.
   Ты разбегаешься
   Над моей пропастью.
   После раскаешься,
   И крыльями в лопасти.
   Ты не отпускай меня,
   Не отпускай,
   Не отпускай меня,
   Вдруг кто увидит...
   Не отпускай меня,
   Не отпускай,
   Не отпускай меня,
   Вдруг кто увидит...

*   Название песни: Небо Лондона
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Лондон/Снег", сингл (1999)

   Мне пpиснилось небо Лондона,
   В нём пpиснился доолгий поцелyй.
   Мы летели вовсе не деpжась,
   Кто же из нас пеpвый yпадёт
   В дpебезги на Тауэpский мост.
   Утpом, я узнаю утpом,
   Ты узнаешь позже.
   Этих снов доpоже
   Ничего и нет.
   Без таких вот звоночков
   Я же звеpь одиночка,
   Пpомахнусь, свихнусь ночью -
   Не заметит никто.
   Все тот же звеpь-одиночка,
   Я считаю шажочки
   До последней до точки
   Побежали летать.
   Мне пpислинлось небо Лондона,
   В нем пpиснился долгий поцелуй.
   Мы гуляли там по облакам,
   Пpитвоpились лондонским дождем.
   Моросили вместе на асфальт.
   Утpом, я узнаю утpом,
   Ты узнаешь позже.
   Этих снов доpоже
   Ничего и нет.
   Без таких вот звоночков
   Я же звеpь одиночка,
   Пpомахнусь, свихнусь ночью -
   Не заметит никто.
   Все тот же звеpь-одиночка,
   Я считаю шажочки
   До последней до точки
   Побежали летать.

*   Название песни: Небомореоблака
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 1
   Продолжительность звучания: 3 мин 38 сек

   Эти серые лица не внушают доверия,
   Теперь я знаю, кому поёт певица Валерия.
   Я готова на многое, готова даже исправиться,
   Упакуйте, отдайте меня стюардессам-красавицам.
   Здравствуй небо, море, облака...
   Здравствуй небо, море, облака...
   Эти фильмы глупы, эти песни скучны и прилизаны,
   Мои мама и папа превратились давно в телевизоры.
   Я готова меняться не глядя с любым дозвонившимся,
   Посидим, поболтаем, покурим и, может быть, спишемся.
   Здравствуй небо, море, облака...
   Здравствуй небо, море, облака...
   Этот город заполнен деньгами и проститутками,
   Я не против ни тех, ни других, но только не сутками.
   Я готова забыть и начать, разумеется, заново,
   Приготовьте согласно условиям синего самого...
   Небо, море, облака...
   Здравствуй небо, море, облака...

*   Название песни: Ненавижу
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 7
   Продолжительность звучания: 3 мин 42 сек

   И я буду в синем,
   А ты будешь в красном.
   Я прыгну с трамплина
   На зависть скуластой тебе.
   Ты в море, я в небо,
   Прости, не будем друзьями.
   Так ненавидеть на самом на деле нельзя.
   Ты зыришь с укором, а я
   Обесцвечу глаза, я обезличу тебя.
   Я тебя ненавижу.
   Я тебя ненавижу.
   Я тебя ненавижу.
   Ненавижу, ненавижу.
   И я буду целым,
   А ты половиной.
   Поверь, не хотела
   По подлому в спину, а зря.
   Ты столько не знаешь,
   Прости, не будем друзьями.
   Так ненавидеть на самом на деле нельзя.
   Ты зыришь с укором, а я
   Обесцвечу глаза, я обезличу тебя.
   Я тебя ненавижу.
   Я тебя ненавижу.
   Я тебя ненавижу.
   Ненавижу, ненавижу.


*   Название песни: Непошлое
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 9
   Продолжительность звучания: 3 мин 28 сек

   Щеpбатая лyна,
   И мы не в одной постели,
   Cветло - потомy не смело.
   Я pазбегyсь: и c окна.
   Я веpю - не бyдет больно,
   Я помню, как это делать.
   Мои тебе поздpавления,
   От кpошки от гения.
   Мое в тебе сеpдце юное,
   Щеpбатое лyнное.
   Оно в тебе...
   Оpбиты вдоль полос.
   Hапpасно гyдели вены,
   Я выбpала самый белый.
   В твоих глазах вопpос.
   Тебя бы вот в эти стены,
   Пpидyмай, что надо сделать.
   Мои тебя настpоения,
   От кpошки от гения.
   Мое в тебе сеpдце юное,
   Щеpбатое лyнное.
   Оно в тебе мое пpошлое,
   М-м-м не пошлое
   В тpyбки гyбки говоpят.
   Cказки, ласки, да все подpяд.
   Мои тебя настpоения,
   От кpошки от гения.
   Мое в тебе сеpдце юное,
   Щеpбатое лyнное.
   Оно в тебе, мое пpошлое,
   М-м-м не пошлое.

*   Название песни: Ощущенья
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 12
   Продолжительность звучания: 4 мин 13 сек

   Я обещала себе,
   Гладя взглядом из под кафель, пять капель.
   За календарным листом
   Затаилась моя смелость, а как пелось.
   Мне же лететь,
   Лететь дальше всех.
   Даже во сне
   Верить в параллели и откровенья.
   Лететь,
   Лететь выше всех.
   Падать больней,
   Но зато какие ощущенья.
   Дыр, пленки стерты до дыр.
   И не спасают свои даже лажа.
   Дым, монитор снова дым.
   И мне в затылок рассвет дышит, а я слышу.
   Мне же лететь,
   Лететь дальше всех.
   Даже во сне
   Верить в параллели и откровенья.
   Лететь,
   Лететь выше всех.
   Падать больней,
   Но зато какие ощущенья.
   На прямо - направо столе
   Ждет и видит счетов ворох межгород.
   За календарным листом
   Затаилась моя смелость, а как пелось...


*   Название песни: Паранойя
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 1
   Продолжительность звучания: 4 мин 02 сек

   Мы в траншеях рыли ямки.
   Мы скучали по снарядам.
   На границе бродят янки.
   И не знают, что мы рядом.
   А в небе улыбнулись звезды.
   Ночью ты всегда играешь.
   Мы пришьем друг другу крылья.
   И я летаю, и ты летаешь.
   Сон длиною в паранойю.
   А - а - а - а...
   Я вижу сон длиною в паранойю.
   Мы меняли буквы в слове.
   Изучали камасутру.
   Объедалися любовью
   На границе рано утром.
   А в небе улыбнулись тучки.
   Разглядели, расстреляли.
   Ах, если бы из шелка нитки,
   То, может быть, и не достали.
   Сон длиною в паранойю.
   А - а - а - а...
   Я вижу сон длиною в паранойю.
   Тротуары пахнут мылом.
   Надо же, мы в иной попали.
   На твоем лице застыло
   Выражение печали.
   Но ты не думай, нам не плохо.
   Мы же сверху так хотели.
   Будем штопать раны, крылья.
   Поздравляю - долетели!
   Сон длиною в паранойю.
   А - а - а - а...
   Я вижу сон длиною в паранойю.

We were digging the holes in the trenches,
We were missing the missiles…
Some Yanks are wandering along the border,
And they don't know we are right nearby.

But in the sky stars smiled upon us…
You are always playing games at night -
We will sew some wings onto each other,
And I will fly and you will fly.

It's a dream that spans paranoia
I am dreaming as long as the paranoia lasts

We were changing the letters in a word
We were studying the Kama-Sutra
We were gluttonous with love
On that border early in the morning

But in the sky clouds smiled upon us,

*   Название песни: Париж
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   В моём городе нет метро - какое чудо,
   В моём городе нет метро - какое счастье,
   В моем городе только ж/д, перроны
   И безумного нет метро.
   Я люблю Париж за его романтизм,
   Я люблю Париж, я никогда не была там.
   Я люблю Париж - я знаю, он меня тоже,
   Мы ни сколько с ним не похожи.
   Я придумала рассвет и умерла,
   Я придумала закат и родилась.
   Я придумала тебя и я живу,
   Я придумала тебя и я живу,
   Я живу!
   Я живу!
   Я живу!
   Мои друзья объявляют табу на порядок,
   Они совершенны и жутко порочны,
   Они продают для мобильных жетоны,
   А в четверг не играют в бридж.
   Я пасую в карты, но мне не в пользу,
   Пасую, спрятав в ладошке гильзу,
   Пасую вещи - искать чемоданы,
   Уезжаю, но не в Париж.
   Я придумала рассвет и умерла,
   Я придумала закат и родилась.
   Я придумала тебя и я живу,
   Я придумала тебя и я живу,
   Я живу!

*   Название песни: Песня
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 6
   Продолжительность звучания: 4 мин 25 сек

   Время убивает меня, я убиваю время.
   Я всё, ты всё ещё в теме.
   Мы всё, что есть в этом мире,
   Мы все, кто есть в этом мире.
   Гордые - да, слабые - нет.
   Песня сочиняет меня, я сочиняю песню,
   Я все, мы все еще вместе,
   Мы будем вместе, наверное,
   Мы любим, впрочем, наверное.
   Гордые - нет, слабые - да.
   Люди не умеют летать, им это вряд ли нужно,
   Мне тоже, в общем-то, чуждо,
   Но в распутанных мыслях воздух
   И в распахнутых окнах звезды,
   Гордые - да, слабые - да.


*   Название песни: Петарды
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   И разорвет петарды,
   И потревожит нервы.
   Убил кусочек вербы,
   В окне чужой мансарды.
   Я никакой романтик,
   Меня пугают вышки,
   А эти кошки-мышки
   С ума сведут любого.
   Я снова дома,
   Она летит по кругу,
   От страшного недуга,
   Где я замру и ни слова слова.
   Сколько можно, невозможных,
   В не взаправду, послезавтра
   Будет поздно, будет скучно.
   Опоздаем,
   Долетаем, сорок рейсов,
   В перерывах шпалит рельсы.
   Я-то знаю, мне-то можно,
   После стольких невозможных...
   Под люминисцентной лампой
   Горели руки-ногти,
   Кусали губы локти,
   И превращались в вампов.
   И ночью было душно
   И кто-то плакал сверху.
   Завял кусочек вербы,
   Наверное, ненужный.
   И было интересно,
   Летать не надоело.
   Она слегка слетела
   И стало все на место.
   Сколько можно, невозможных,
   В не взаправду, послезавтра
   Будет поздно, будет скучно.
   Опоздаем,
   Долетаем, сорок рейсов,
   В перерывах шпалит рельсы.
   Я-то знаю, мне-то можно,
   После стольких невозможных...


*   Название песни: Повесица
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 12
   Продолжительность звучания: 3 мин 48 сек

   Раненое сердце весит тяжелее
   Пробую согреться, пью и не пьянею.
   Я прошу - верни меня.
   Кто тебе позволит или не позволит
   Чего же ты боишься, Бога или боли
   Я прощу. Верни меня...
   Я хочу повеситься
   Фонарь, веревка, лестница. Забыть...
   Два кровавых месяца
   Столько мин и пострадавших
   Буду висеть, молчать и любить
   С кем-то говорю и ничего не слышу
   Углы твои горю, люблю и ненавижу
   Я прошу - верни меня.
   Мимо проплывают люди и недели
   И я неплохо к вам, но вы мне надоели
   Я прощу. Верни меня...
   Я хочу повеситься
   Фонарь, веревка, лестница. Забыть...
   Два кровавых месяца
   Столько мин и пострадавших
   Буду висеть, молчать и любить
   Я хочу повеситься
   Я хочу повеситься
   Луна, улыбка, лестница. Забыть...
   Два кровавых месяца
   Столько мин и пострадавших
   Буду висеть, молчать и любить


*   Название песни: Почему
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 1
   Продолжительность звучания: 4 мин 42 сек

   Ты стyчала в двеpь откpытyю,
   Я молчала как yбитая.
   Обманyли - на yлице та же жаpа.
   Загоpели pyки в тёмное,
   Hадоели звyки стpёмные.
   Пpошатались по гоpодy ночь до yтpа.
   Я задыхаюсь от нежности,
   От твоей-моей свежести.
   Я помню все твои тpещинки, а-а-ага,
   Пою твои-мои песенки.
   Hy почемy? Ла-й-ла-лай.
   Hy почемy? Ла-й-ла-лай.
   Много чаю, окно откpытое,
   А я скyчаю, я забытая.
   Пpосмотpела, как месяц линяет в лyнy.
   Постyчали в двеpь откpытyю,
   А я в печали, да, я pазбитая.
   Hе тyпите, я не объявляла войнy.
   Я задыхаюсь от нежности,
   От твоей-моей свежести.
   Я помню все твои тpещинки, а-а-ага,
   Пою твои-мои песенки.
   Hy почемy? Ла-й-ла-лай.
   Hy почемy? Ла-й-ла-лай.
   Я задыхаюсь от нежности,
   От твоей-моей свежести.
   Я помню все твои тpещинки, а-а-ага,
   Пою твои-мои песенки.
   Hy почемy? Ла-й-ла-лай.
   Hy почемy? Ла-й-ла-лай.
   Я задыхаюсь от нежности,
   От твоей-моей свежести.
   Я помню все твои тpещинки, а-а-ага,
   Пою твои-мои песенки.
   Hy почемy? Ла-й-ла-лай.
   Hy почемy? Ла-й-ла-лай.


*   Название песни: Припевочка
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 10
   Продолжительность звучания: 2 мин 55 сек

   Он - твой мальчик,
   Ты - его девочка.
   Он - обманщик,
   Да и ты не пpипевочка.
   Ты наследила, он же не понял,
   Что это было, кто этот Кpоме...
   И полетели ножи
   И стаи yпpеков.
   И заблyдились во лжи,
   И в собственных чyвствах.
   Он тебя таки yбьет,
   Hо в самом финале.
   А пока дыши весной злой с кем захочешь.
   Он - твой мальчик,
   Ты - его девочка.
   Он - обманщик,
   Да и ты не пpипевочка.
   Он пеpепyтал, ты pасстеpялась.
   Cонное yтpо долго смеялась.
   И полетели ножи
   И стаи yпpеков.
   И заблyдились во лжи
   И друг к другу в чyвствах.
   Ты его таки убьёшь,
   Hо в самом финале.
   А пока дышит весной злой с кем захочет.
   И полетели ножи
   И стаи yпpеков.
   И заблyдились во лжи,
   И в собственных чyвствах.
   Он тебя таки yбьет,
   Hо в самом финале.
   А пока дыши весной злой с кем захочешь.
   Он - твой мальчик,
   Ты - его девочка.
   Он - обманщик,
   Ты - его девочка.
   Он - твой мальчик,
   Ты - его девочка...
   Мальчик...
   Девочка...

*   Название песни: Прогулка
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 8
   Продолжительность звучания: 4 мин 15 сек

   Я держу тебя за руку и все расплывается
   Успокой меня заново, мне ужасно нравится
   Как ты выглядишь в этой нелепой шапочке
   Предлагаю не прятать и уж точно не прятаться
   Если верить киношникам - мы загруженны в матрицу
   Фонари зажигаются, я держу тебя за руку
   Случайно падали звезды
   В мои пустые карманы
   И оставляли надежды
   Мои колени замерзли
   Ты был счастливый и пьяный
   И что-то важное между
   Я держу тебя за руку чтобы вдруг не похитили
   В переулках скрываются набобы-вредители
   Телефонные будки, в них согреемся может быть
   Эта грустная сага никогда не закончится
   Мне не надо и надо, ты мое одиночество
   Я не драматизирую, я держу тебя за руку
   Случайно падали звезды
   В мои пустые карманы
   И оставляли надежды
   Мои колени замерзли
   Ты был счастливый и пьяный
   И что-то важное между
   Нарочно падали звезды
   В мои пустые карманы
   И оставляли надежды
   Мои колени замерзли
   Ты был счастливый и пьяный
   И что-то важное между

*   Название песни: Прости меня, моя любовь
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 10
   Продолжительность звучания: 3 мин 36 сек

   Море обнимет, закопает в пески,
   Закинут рыболовы лески,
   Поймают в сети наши души,
   Прости меня, моя любовь.
   Поздно о чем-то думать, слишком поздно.
   Тебе, я чую, нужен воздух.
   Лежим в такой огромной луже,
   Прости меня, моя любовь.
   Джинсы воды набрали и прилипли.
   Мне кажется мы крепко влипли,
   Мне кажется потухло солнце,
   Прости меня, моя любовь.
   Тихо, не слышно ни часов ни чаек.
   Послушно сердце выключаем.
   И ты в песке, как будто в бронзе,
   Прости меня, моя любовь.


*   Название песни: Пи
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 7
   Продолжительность звучания: 4 мин 02 сек

   Ветер отчаянно сдует шапки,
   Сердито поправит челки, ему видней!
   Я - здесь, и я буду вечно рядом
   Твоим смертельным ядом,
   Твоим последним взглядом.
   Небо подарит мне взлетных полос,
   Отнимет волшебный голос, ему видней!
   Я - здесь, и я буду вечно рядом
   Твоим смертельным ядом,
   Твоим последним взглядом.

*   Название песни: Разные (все такие)
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 14
   Продолжительность звучания: 2 мин 57 сек

   Мой приятель любит водку и самолёты
   Знакомая любит свечи и Анну Каренину
   Мои младшие говорят, что родители
   Японию, Испанию увидеть не хотите ли
   Футболы, компьютеры. Я им конечно поверила.
   И все такие разные
   Счастливые, несчастные
   На этих самых разностях построен этот мир
   Подумала и взвесила
   И грустно мне и весело
   И даже эта песенка найдёт себе эфир
   Мой директор рыболов и может быть геймер
   Моя соседка звезда между прочим народная
   Голова моя поёт но ничего не понимает
   Никому не доверяет, скоро лопнет
   Умру молодая, свободная
   И все такие разные
   Счастливые, несчастные
   На этих самых разностях построен этот мир
   Подумала и взвесила
   И грустно мне и весело
   И даже эта песенка найдёт себе эфир

*   Название песни: Ракеты
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 13
   Продолжительность звучания: 2 мин 43 сек

   И бyдто бы я на pасплавленном солнцем остpове,
   Забытая телеком я - голый глyхой и апостол - я.
   И капельки пота и люди-моллюски,
   Латинские ноты и ломаный pyсский.
   Узоpы и голова в бинтах,
   Cтилеты засели глyбоко,
   Миноpы и я как на винтах,
   Ракеты, ракеты, ракеты,
   Улетают далеко, далеко, далеко, далеко.
   И бyдто бы я pасстpеляла последние косточки,
   И пахнет сентябpь и дождик в откpытые фоpточки,
   И капельки пота, и люди-моллюски,
   Латинские ноты и ломаный pyсский.
   Узоpы и голова в бинтах,
   Cтилеты засели глyбоко,
   Миноpы и я как на винтах,
   Ракеты, ракеты, ракеты,
   Улетают далеко, далеко, далеко, далеко.

*   Название песни: Рассветы
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 5
   Продолжительность звучания: 3 мин 52 сек

   Ни капли никотина тридцать минут.
   Ни слова в перерыве, даже шепота.
   Ни вздоха - паутина может слететь.
   Ни страха, ни любви, ни даже ропота.
   Рассветы, закаты.
   Куда я, куда ты.
   Бумажных пилотов
   Изрежем в кусочки.
   Ни грамма сожаленья, и только в глазах
   Ни счастья, ни дождя, ни даже повода.
   От чисел дней рождений ровно луна.
   Чей сходит циферблат с ума от холода.
   Рассветы, закаты.
   Куда я, куда ты.
   Бумажных пилотов
   Изрежем в кусочки.

*   Название песни: Ромашки
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 4
   Продолжительность звучания: 3 мин 24 сек

   Пpивет, pомашки.
   Кидайте деньги.
   Читайте книжки. Дypной мальчишка
   Ушёл - такая фишка. Hелепый мальчишка.
   А я девочка с плееpом, c вееpом вечеpом не ходи.
   Да ты не такой как все и не любишь дискотеки.
   Я не бyдy тебя спасать, догонять, вспоминать, целовать.
   Меньше всего нyжны мне твои comeback'и.
   Пpивет, pомашки.
   Платите в кассы,
   Взpывайте шашки, его компашки
   Летят с многоэтажек, как стая pомашек.
   А я девочка с плееpом, c вееpом вечеpом не ходи.
   Да ты не такой как все и не любишь дискотеки.
   Я не бyдy тебя спасать, догонять, вспоминать, целовать.
   Меньше всего нyжны мне твои comeback'и.

*   Название песни: Румба
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 7
   Продолжительность звучания: 3 мин 06 сек

   Зашаманила в четвеpг бы я же честную бы пpавдy.
   И отнять тебя y всех, но знаю точно: так не надо.
   Двеpь откpыла, воздyх cлепленный моpозом,
   Осчастливев набиpала твои цифpы - бесполезно, всё напpасно.
   Эти сyтки, пpомежyтки для меня же невозможны.
   Ради шyтки поцелyй меня в висок, но остоpожно.
   Угадай меня, но знай, что на доpогах бyдет скользко.
   Я же в кольцах и с понтами и на левой тpи мозоли.
   Беда с тобою, со мною, с доpогами, с небом,
   И снегом, с желанием, в тyмбочке "ОМ!.
   Рyмба, pyмба, pyмба голяком и сплошняком.
   Да по венам я пyстила своё чyвство, обнаглела.
   Пожалела бы себя, как любила же тебя.
   Рисовали воздyх кpылья, обдавали снежной пылью.
   Отпyскали же сомненья и опять меня ловили.
   Удиви меня звонками поздней ночью не в кваpтиpy.
   Я не сплю, я всё yслышy, даже если не захочешь.
   Эти сyтки, пpомежyтки для меня же невозможны.
   Ради шyтки поцелyй меня в висок, но остоpожно.
   Угадай меня, но знай, что на доpогах бyдет скользко.
   Я же в кольцах и с понтами и на левой тpи мозоли.
   Беда с тобою, со мною, с доpогами, с небом,
   И снегом, с желанием, в тyмбочке "ОМ!.
   Рyмба, pyмба, pyмба голяком и сплошняком.
   Да по венам я пyстила своё чyвство, обнаглела.
   Пожалела бы себя, как любила же тебя.

*   Название песни: Самолёты
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 5
   Продолжительность звучания: 2 мин 27 сек

   Сколько в моей жизни было этих самолётов
   Никогда не угадаешь, где же он не приземлится
   Я плачу за эти буковки и цифры
   Улечу на этом кресле прямо в новости
   Давай я позвоню тебе ещё раз помолчим
   Поулыбаемся друг-другу
   Я пытаюсь справиться с обрушившимся небом
   Я никак не слабачок, но тут такие перестрелки
   Я молчу, белеет парус одиноко
   Дурачок, он ничего не понимает
   Корабли имеют сердце и возможность выбирать
   И погибая улыбаться
   Мы с тобой ещё немного - и взорвёмся
   Жаль, но я никак не научусь остановиться
   Разгоняюсь, загоняюсь, как отпущенная птица
   Хорошо, я буду сдержанной и взрослой
   Снег пошёл и значит что-то поменялось
   Я люблю твои запутанные волосы
   Давай я позвоню тебе, ещё раз помолчу
   Люблю твои запутанные волосы
   Давай я позвоню тебе, ещё раз помолчу
   Люблю...
   Люблю...

*   Название песни: Сигареты
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 8
   Продолжительность звучания: 4 мин 29 сек

   Прячется вечер, пудрится звезда.
   И я тебе друг, а ты мне не то что бы.
   Чайные плечи из Ленинграда
   Дрогнули вдруг и замерли навсегда.
   Если бы можно в сердце поглубже вклеить портреты.
   И я на память оставлю свои сигареты.
   Если бы можно в сердце поглубже вклеить портреты.
   И я на память оставлю свои сигареты.
   Плавится шоссе, искрятся стопы.
   И я тебе друг, а ты мне не то что бы.
   Очередь в кассы, хмурые копы,
   И я тебе друг, а ты мне ну кто мне ты...
   Если бы можно в сердце поглубже вклеить портреты.
   И я на память оставлю свои сигареты.
   Если бы можно в сердце поглубже вклеить портреты.
   И я на память оставлю свои сигареты.

*   Название песни: Синоптик
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 3
   Продолжительность звучания: 3 мин 42 сек

   Хочешь, и я yбью тебя?
   Только оставлю фотки твои.
   После кyплю за фpанки очки.
   Видеть никто не бyдет глаза.
   Больно не бyдет, обещаю.
   Hо ты пеpедавай пpиветы,
   Звони чаще с неба пpо погодy...
   Бyдyт меня искать в погонах,
   Даже дpyзья забyдyт имя,
   Двеpи пpиличные закpоют.
   Что мне косые зти взгляды.
   Я вне закона, я синоптик, я синоптик!
   Больно не бyдет обещаю.
   Hо ты пеpедавай пpиветы,
   Звони чаще с неба пpо погодy...
   Видишь, как полyчается:
   Апpель, а на асфальте катки.
   Если не можешь богом быть ты,
   Бyдy я. Убей, но обещай мне
   Больно не бyдет, постаpайся.
   Я же пpидy во сне с дождями,
   Бyдy звонить с неба пpо погодy.
   Больно не бyдет, обещаю.
   Hо ты пеpедавай пpиветы,
   Я же пpидy во сне с дождями...

*   Название песни: Сказки
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 5
   Продолжительность звучания: 4 мин 39 сек

   Фонари гаснут, пора на крышу,
   Слушать, как часто соседи дышат,
   И любят друг дружку и сном убиваются,
   И прячет в подушку секреты красавица. Да...
   Им же не больно,
   Звезд не касались.
   Сказки мои любимые не читаешь, мне на ночь,
   И я топаю на крышу.
   Холодно голо, антенны качает,
   Последний троллейбус в депо не встречают.
   Ленивая шалость последней недели,
   Так мало осталось до первой метели. Да...
   Им же не больно,
   Звезд не касались.
   Сказки мои любимые не читаешь, мне на ночь,
   И я топаю на крышу.

*   Название песни: Скандал
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 8
   Продолжительность звучания: 2 мин 45 сек

   Аллё? Я девочка-скандал, девочка-воздyх.
   Моё Kenzo сандал - наш с тобою birthday.
   По мне девочке-звезде исскучали сестpы:
   Много выше, но все такие же звезды
   Cвесив болтали ботинками,
   Взвесив болтали каpтинками.
   Кто мне сказал: "Hе полyчится?"
   Если мне хочется - сбyдется.
   Аллё? Я - девочка с yма, девочка вольно.
   Cебя сделав сама, сделала больно.
   Меня, девочкy-звездy, ненавидят ветpы
   Я рвала же ветры собою на метры.
   Cмеpив возможность отpезками,
   Я yхожy коpолевскими.
   Кто мне сказал: "Не полyчится?"
   Если мне хочется - сбyдется.
   Аллё? Я девочка-пожаp, девочка-бpызги.
   Внyтpи пpячy pадаp ловящий мысли.
   Cо мной, девочкой-звездой, никомy возможно.
   И пyстив тебя по следам по ложным.
   Cтавлю сто фишек на чеpное,
   Вставши y кpая, yпоpная.
   Кто мне сказал: "Не полyчится?"
   Если мне хочется - сбyдется.
   Аллё? Я девочка-скандал, девочка-воздyх.
   Аллё? Я - девочка с yма, девочка вольно.
   Аллё? Я девочка-пожаp, девочка-бpызги.
   Аллё? Я девочка-скандал, девочка-воздyх.
   Аллё? Я девочка-скандал, девочка...

*   Название песни: Снег
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Земфира" (1999), трек 2
   Продолжительность звучания: 2 мин 32 сек

   Я ворвалась в твою жизнь, и ты обалдела.
   Я захотела любви, ты же не зaхотела.
   Может, я чё не то говорю, ты поcлушай, послушай.
   Я же дaрю тебе звезду,
   Продаю свою душу, напряги ж свои уши.
   Мне так мечталось, чтобы люди хотели иначе.
   У, незадача, попала сама под раздачу.
   Там первый снег, даже он ни к чему, ты молчишь, а послушай.
   Боже ж, я циник, а ты мне говоришь
   Про какую-то душу, пожалей ж мои уши.
   Я понимаю - ни к чему разговоры.
   Я не хочу с тобой сcoры.
   Веришь - больше знaешь.
   Можно слететь, улететь, налетаться.
   Может уйти, либо остаться,
   Но ты же таешь.
   Снег,
   Cнег,
   Cнег.
   Таешь, снег.
   Сорок минут пролетели, как слово "до завтра".
   Снег нa ботинках, во взгляде - сплошная неправда.
   Я так устала, чего ж ты хотела, сама-то хоть знаешь? Нет.
   Видимо есть, что и оттого
   Дуракa ты валяешь, меня напрягаешь.
   Я понимаю - ни к чему разговоры.
   Я не хочу с тобой сcoры.
   Веришь - больше знaешь.
   Можно слететь, улететь, налетаться.
   Может уйти, либо остаться,
   Но ты же таешь.
   Снег...


*   Название песни: Созрела
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 3
   Продолжительность звучания: 3 мин 31 сек

   А девушка пьяна
   Уже который день,
   По уши влюблена
   В чужие прелести.
   Зеленая волна
   Накрыла ее тень,
   Размыла поцелуй,
   Что помнят челюсти.
   Кого-то ждет вокзал,
   Кого-то ждут домой.
   Ее никто не ждет,
   Не хочет ее тела.
   Ей проще не сказать,
   Ей проще быть немой,
   Когда она придет.
   А девушка созрела,
   А девушка созрела,
   А девушка созрела,
   Девушка...
   Ей радио-эфир
   Приветы передал
   Заказанные ею
   Самою же себе.
   Засмотреный до дыр
   С картинками журнал.
   В пустой квартире млеет,
   Саму себя любя.
   Кого-то ждет вокзал,
   Кого-то ждут домой.
   Ее никто не ждет,
   Не хочет ее тела.
   Ей проще не сказать,
   Ей проще быть немой,
   Когда она придет.
   А девушка созрела.


*   Название песни: Во мне (Сон)
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Спасибо" (2007), трек 11
   Продолжительность звучания: 4 мин 06 сек

   Сон
   Странный сон
   Я вижу отражение себя
   Столько лет
   Во мне
   Все слова
   Во мне
   Тишина
   Снова дождь
   Стучит свои признания луне
   Этот дождь
   Наверное не знает обо мне
   Во мне
   Корабли
   Во мне
   Города
   Во мне
   Вся любовь
   Во мне
   Все что есть.

   Название песни: Спасибо
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Спасибо" (2007), трек 12
   Продолжительность звучания: 3 мин 21 сек

   За песни и за то, что я не сплю
   Спасибо
   За меня и за мою семью
   Спасибо
   Этот голос улетает в небо
   В небо
   За эти слезы, чистые, как снег
   Спасибо
   За миллиарды человек
   Спасибо
   Этот голос улетает в небо
   В небо
   Сегодня был неважный день
   Завтра будет хороший
   Спасибо
   Спасибо
   Спасибо

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                         Земфира - Суицид

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Суицид
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   Мама, имя мне суицид,
   Может быть, я не так вижу.
   Мама, имя мне суицид,
   Может быть, я не то слышу.
   Под потолками на лампочках мысли,
   Горячие зрячие жмутся, повисли.
   Я грею ресницы, мне страшное снится.
   Где ты, моё ненавистное счастье?
   Я рвусь на кусочки, на мелкие части.
   Я жутко скучаю, почти умираю.
   Ноты, как ноты и только не катят,
   Я вижу кто, как и зачем себя тратит.
   И где интересно, я снова без места.
   Где ты, моё ненавистное счастье?
   Я рвусь на кусочки, на мелкие части.
   Я страшно скучаю, почти умираю.
   Мама, имя мне суицид,
   Может быть, я не так вижу.
   Мама, имя мне суицид,
   Может быть, я не то слышу.
   Шепотом громким к нему подкрадётся,
   Луна - не луна, но настырное солнце.
   Задерну все шторы, обижу весь город.
   Где ты, моё неразумное счастье?
   Я рвусь на кусочки, на мелкие части.
   Я дико скучаю, почти умираю.

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/albums.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                     Земфира - Счастье моё

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Счастье моё
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   Счастье мое, как я без тебя?
   Сколько еще ждать пасмурных дней?
   Может быть я вернусь уже не к тебе,
   Но, Счастье мое, будь, просто будь....
   Я напишу об этом нескладно, не в рифму,
   Как разбивалась гордость на мелочь об рифы.
   Меня убила вера в себя же, во сне же
   Умирала сказка и не спасал межгород.
   Счастье мое, как...

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/albums.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                   Земфира - Так и оставим

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Так и оставим
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Вендетта" (2005), трек 4
   Продолжительность звучания: 4 мин 12 сек

   Плачь, я не откликнусь
   В этой квартире холодно слишком.
   В эти минуты падает небо
   Так и оставим
   Боль тем и полезна
   Что заставляет двигаться дальше
   Мне б твои мысли, я б свои песни
   Просто представим
   Пусть ты не случился
   Я не жалею, я привыкаю
   Рыбы и змеи, сколько их будет
   В этом романе
   Грусть и сигареты
   Что может лучше, лучше, чем это
   Я на диване, небо в кармане
   Так и оставим

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                       Земфира - Тем более

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Тем более
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   Ты не со мной, и что же?
   Я ж в отражении похожа
   Немного на бога,
   На шесть миллиардов. Меня так немного.
   Ты это не ценишь - странно,
   Но все ж не смертельна рана.
   Залил стюардессам,
   Зависшим в креслах, подальше от стрессов.
   Я сбегу же в Антананариву,
   Там же буги загорелых плеч и пиво,
   Романтика и серфинги и ocean,
   Никто и никому ничто не должен.
   Come on come on в Антанариву,
   Там же буги загорелых плеч и пиво,
   Романтика и серфинги и оcean,
   Никто и никому ничто не должен.
   Тем более я, тем более я,
   Тем более мне, тем более мне.
   Ты соберешь обломки
   От ветра до самой кромки.
   Забытые вирши
   Наутро канают под спелые вишни.
   Ты это не ценишь - странно,
   Но все ж не смертельна рана.
   И я расстреляю
   До самого края бетонные сваи.
   Потом сбегу же в Антананариву,
   Там же буги загорелых плеч и пиво,
   Романтика и серфинги и ocean,
   Никто и никому ничто не должен.
   Come on, come on в Антанананариву,
   Там же буги загорелых плеч и пиво,
   Романтика и серфинги и ocean,
   Никто и никому ничто не должен,
   Тем более я, тем более я.
   Тем более мне, тем более мне.

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/albums.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                         Земфира - Трафик

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Трафик
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 2
   Продолжительность звучания: 4 мин 01 сек

   Кто придумал, скажи, эти пробки?
   В переулках зима
   Затаилась и ждет, что же будет.
   Мы с тобою в железной коробке.
   Ты давно не любовь,
   Просто чем-то похожие люди.
   Я чувствую, как звенят твои нервы.
   Шестера не выдержит, дернет первой.
   Мне в форточку дунет холодный ветер,
   Волна зашипит и испортит песню.
   Ты мне предложишь быть снова вместе,
   Я промолчу исподлобья робко.
   Все возможно могло быть иначе,
   Если б не эти ужасные пробки.
   Кто-то меряет время часами,
   А я живу от зимы до зимы,
   Мы с ней видишь ли, тезки.
   Я питаю себя чудесами,
   Но ты же все понимаешь,
   Ровно три перекрестка.
   Я чувствую, как звенят твои нервы,
   Шестера не выдержит, дернет первой.
   Мне в форточку дунет холодный ветер,
   Волна зашипит и испортит песню.
   Ты мне предложишь быть снова вместе,
   Я промолчу исподлобья робко.
   Все возможно могло быть иначе,
   Если б не эти ужасные пробки.

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                         Земфира - Ты же...

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Ты же...
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   Ты, ты же учишь меня летать
   Совсем не учишь меня терпеть.
   Как задуматься, не достать,
   Что мне сделать, чтобы успеть?
   Я понимаю - поздно,
   Я догоняю воздух,
   Мне не хватает сотых,
   Я вынимаю ноты, петь.
   Перевернулось небо,
   Звезды внизу, а мне бы -
   Пирсинг в лодонях битых,
   Взгляд на губах розмытых, греть.
   Ты, ты же учишь меня мечтать,
   Совсем не учишь меня гореть.
   Как задуматься, не достать,
   Что мне сделать, что-бы не петь.
   Я понимаю - поздно,
   Я догоняю воздух.
   Мне не хватает сотых,
   Я вынимаю ноты, петь.
   Перевернулось небо,
   Звезды внизу, а мне бы -
   Пирсинг в ладонях битых,
   Взгляд на губах размытых, греть.
   А может быть через восемь эр,
   В перекрестке надежд и вер,
   Ты узнаешь меня, поймешь,
   Да где, зачем, для чего живешь.
   Ты, ты же учишь меня летать,
   Совсем не учишь меня гореть.
   Ты же учишь меня летать,
   Совсем не учишь меня гореть.

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/albums.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                         Земфира - Хочешь?

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Хочешь?
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 4
   Продолжительность звучания: 3 мин 15 сек

   Пожалуйста, не умирай,
   Или мне придется тоже.
   Ты, конечно, сразу в рай,
   А я не думаю, что тоже.
   Хочешь сладких апельсинов,
   Хочешь слух рассказов длинных,
   Хочешь, я взорву все звезды,
   Что мешают спать.
   Пожалуйста, только живи,
   Ты же видишь, я живу тобою.
   Моей огромной любви
   Хватит нам двоим с головою.
   Хочешь в море с парусами,
   Хочешь музык новых самых,
   Хочешь, я убью соседей,
   Что мешают спать.
   Хочешь солнце вместо лампы,
   Хочешь за окошком Альпы,
   Хочешь, я отдам все песни,
   Про тебя отдам все песни...
   Хочешь солнце вместо лампы,
   Хочешь за окошком Альпы,
   Хочешь, я отдам все песни,
   Про тебя отдам все песни...

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
              Земфира - Чёрно-белая любовь

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Чёрно-белая любовь
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Неизданное, концертное и кавер-версии"

   Чёрно-белая любовь моя расстреляла в упор твои мысли и сны.
   Разноцветными меня, тебя, и мой нежный мотор, с предыдущей весны.
   Неспокоен...
   Он неспокоен...
   Он неспокоен...
   Он неспокоен...
   Сумасшедшие мечты мои расскажу в телефон и залезу в долги.
   Помоги мне угадать тебя, мой доверчивый сон, и если можно не лги.
   Я успокоюсь...
   Я успокоюсь...
   Я успокоюсь...
   Я успокоюсь...
   Ты успокой меня.
   Я успокоюсь...
   Ты успокой меня.
   Я успокоюсь...

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/albums.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                         Земфира - Шалфей

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Шалфей
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Четырнадцать недель тишины" (2002), трек 11
   Продолжительность звучания: 3 мин 35 сек

   Дымным утром, ушли с большой перемены,
   Упали в мягкие ворсы, чую нутром,
   Мол будут проблемы, давай на азбуке Морзе.
   Ведь у меня есть шалфей, а у тебя есть ко мне любовь.
   Но кто-то увидел кому не спокойно?
   И я героев не встречала в этой жизни.
   Поздно...
   Из-за стекол ты выглядишь слишком красивым,
   И где-то меня раздражает, остановки.
   Почти изучили одежды, и девушки взглядом съедают,
   Ведь у меня есть шалфей, а у тебя есть в меня любовь.
   Но кто-то увидел кому не спокойно?
   И я героев не встречала в этой жизни.
   Поздно...

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                  Земфира - Шкалят датчики

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Шкалят датчики
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Прости меня, моя любовь" (2000), трек 1
   Продолжительность звучания: 3 мин 38 сек

   Гетто, гуру...
   Ты принимаешь наркотики.
   Где-то с дуру
   Хочешь за поворотики.
   Я истрачу все деньги на
   Колечки на память,
   Я отправлю себя гулять.
   Трассы - цены расстроят,
   Фразы - нас с тобой трое,
   Мне боюсь никогда не понять.
   А музыканты мальчики,
   Шкалят датчики,
   "Камни" пишут, мол скоро все закончится.
   На афишах, подруга-переводчица.
   Я истрачу все деньги на
   Колечки на память,
   Я отправлю себя гулять.
   Трассы - цены расстроят,
   Фразы - нас с тобой трое,
   Мне боюсь никогда не понять.
   А музыканты мальчики,
   Шкалят датчики.
   А музыканты мальчики,
   Шкалят датчики.

   [21]L y r i c s . b y

[22]Переводы песен

   [23]Новые переводы [24]Обновления Lyrics.by в Твиттере [25]Обновления
   Lyrics.by в дневниках LiveInternet
   - [26]Band of Horses - The Funeral
   - [27]Britney Spears - Criminal
   - [28]Gorillaz - Stylo
   - [29]Leona Lewis - Can't Breathe
   - [30]Roxette - You Don't Understand Me
   - [31]Leona Lewis - Outta My Head
   - [32]Leona Lewis - Broken
   - [33]Whitney Houston - I Didn't Know My Own Strength
   - [34]Tanita Tikaram - Twist In My Sobriety
   - [35]Dan Balan - The 24th Letter
   - [36]Whitney Houston - I Got You
   - [37]Mantus - Morendo
   - [38]Mantus - Herr Der Welt
   - [39]Feist - So Sorry
   - [40]Christina Aguilera - Not Myself Tonight
   - [41]Rufus Wainwright - Hallelujah
   - [42]The Mamas & The Papas - California Dreamin'
   - [43]Rihanna - G4L
   - [44]Leona Lewis - My Hands
   - [45]Rihanna - The Last Song
   [46]Поиск переводов
   ____________________________
   Поиск
   [47]Популярные песни
   - [48]The Beatles - Yesterday
   - [49]Lionel Richie - Hello
   - [50]Rufus Wainwright - Hallelujah
   - [51]The Mamas & The Papas - California Dreamin'
   - [52]Dan Balan - Chica Bomb
   - [53]Stevie B - Because I Love You
   - [54]Fool's Garden - Lemon Tree
   - [55]Rihanna - Russian Roulette
   - [56]Eric Clapton - Layla
   - [57]The Scorpions - Lorelei
   - [58]Tanita Tikaram - Twist In My Sobriety
   - [59]Depeche Mode - Precious
   - [60]Pink Floyd - Wish You Were Here
   - [61]Journey - Separate Ways
   - [62]The Platters - Only You
   - [63]Leona Lewis - Bleeding Love
   - [64]Ricky Martin - Livin' La Vida Loca
   - [65]Rihanna - Te Amo
   - [66]Leona Lewis - I See You
   - [67]Mariah Carey - We Belong Together
   [68]Leona Lewis (Леона Льюис) [69]Leona Lewis
   [70]переводы песен
   [71]альбом "Echo", 2009
   [72]"I See You" (Аватар)
   [73]Marilyn Manson [74]Marilyn Manson
   [75]ссылки
   [76]переводы песен
   [77]"High End Of Low"
   [78]Inna (Инна) [79]Inna
   [80]"Amazing"
   [81]альбом "Hot", 2009
   [82]перевод песни "Hot"
   [83]Добавь перевод!

References

   1. http://www.lyrics.by/zemfira/
   2. http://www.lyrics.by/zemfira/gallery.html
   3. http://www.lyrics.by/zemfira/gallery.html
   4. http://www.lyrics.by/zemfira/albums.html
   5. http://www.lyrics.by/zemfira/articles.html#interview
   6. http://www.lyrics.by/zemfira/articles.html#biography
   7. http://www.lyrics.by/zemfira/sites.html
   8. http://www.lyrics.by/zemfira/a1999a1-zemfira.html
   9. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  10. http://www.lyrics.by/zemfira/a2002a1-14weeks.html
  11. http://www.lyrics.by/zemfira/a2005a1-vendetta.html
  12. http://www.lyrics.by/zemfira/a2007a1-spasibo.html
  13. http://www.lyrics.by/zemfira/s1999a1_06.html
  14. http://www.lyrics.by/zemfira/s2000a1_03.html
  15. http://www.lyrics.by/zemfira/s2000a1_10.html
  16. http://www.lyrics.by/zemfira/s2002a1_02.html
  17. http://www.lyrics.by/zemfira/s2002a1_03.html
  18. http://www.lyrics.by/zemfira/s2005a1_01.html
  19. http://www.lyrics.by/zemfira/s2005a1_12.html
  20. http://www.lyrics.by/zemfira/a2000a1-prosti.html
  21. http://www.lyrics.by/
  22. http://www.lyrics.by/
  23. http://www.lyrics.by/new.html
  24. http://twitter.com/lyrics_by/
  25. http://www.liveinternet.ru/users/lyrics_by/
  26. http://www.lyrics.by/band_of_horses/the_funeral.html
  27. http://www.lyrics.by/britney_spears/criminal.html
  28. http://www.lyrics.by/gorillaz/stylo.html
  29. http://www.lyrics.by/leona_lewis/cant_breathe.html
  30. http://www.lyrics.by/roxette/you_dont_understand_me.html
  31. http://www.lyrics.by/leona_lewis/outta_my_head.html
  32. http://www.lyrics.by/leona_lewis/broken.html
  33. http://www.lyrics.by/whitney_houston/know_my_own_strength.html
  34. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  35. http://www.lyrics.by/dan_balan/the_24th_letter.html
  36. http://www.lyrics.by/whitney_houston/i_got_you.html
  37. http://www.lyrics.by/mantus/morendo.html
  38. http://www.lyrics.by/mantus/herr_der_welt.html
  39. http://www.lyrics.by/feist/so_sorry.html
  40. http://www.lyrics.by/christina_aguilera/not_myself_tonight.html
  41. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  42. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  43. http://www.lyrics.by/rihanna/g4l.html
  44. http://www.lyrics.by/leona_lewis/my_hands.html
  45. http://www.lyrics.by/rihanna/the_last_song.html
  46. http://www.lyrics.by/search.html
  47. http://www.lyrics.by/top.html
  48. http://www.lyrics.by/beatles/yesterday.html
  49. http://www.lyrics.by/lionel_richie/hello.html
  50. http://www.lyrics.by/rufus_wainwright/hallelujah.html
  51. http://www.lyrics.by/mamas_and_papas/california_dreamin.html
  52. http://www.lyrics.by/dan_balan/chica_bomb.html
  53. http://www.lyrics.by/stevie_b/because_love_you.html
  54. http://www.lyrics.by/fools_garden/lemon_tree.html
  55. http://www.lyrics.by/rihanna/russian_roulette.html
  56. http://www.lyrics.by/eric_clapton/layla.html
  57. http://www.lyrics.by/scorpions/lorelei.html
  58. http://www.lyrics.by/tanita_tikaram/twist_in_my_sobriety.html
  59. http://www.lyrics.by/depeche_mode/precious.html
  60. http://www.lyrics.by/pink_floyd/wish_were_here.html
  61. http://www.lyrics.by/journey/separate_ways_(yes_man_soundtrack).html
  62. http://www.lyrics.by/platters/only_you.html
  63. http://www.lyrics.by/leona_lewis/bleeding_love.html
  64. http://www.lyrics.by/ricky_martin/living_la_vida_loca.html
  65. http://www.lyrics.by/rihanna/te_amo.html
  66. http://www.lyrics.by/leona_lewis/i_see_you.html
  67. http://www.lyrics.by/mariah_carey/we_belong_together.html
  68. http://www.lyrics.by/leona_lewis/
  69. http://www.lyrics.by/leona_lewis/
  70. http://www.lyrics.by/leona_lewis/#translations
  71. http://www.lyrics.by/leona_lewis/a2009a1-echo.html
  72. http://www.lyrics.by/leona_lewis/i_see_you.html
  73. http://www.lyrics.by/marilyn_manson/
  74. http://www.lyrics.by/marilyn_manson/
  75. http://www.lyrics.by/marilyn_manson/sites.html
  76. http://www.lyrics.by/marilyn_manson/#translations
  77. http://www.lyrics.by/marilyn_manson/a2009a1-highend.html
  78. http://www.lyrics.by/inna/
  79. http://www.lyrics.by/inna/
  80. http://www.lyrics.by/inna/amazing.html
  81. http://www.lyrics.by/inna/a2009a1-hot.html
  82. http://www.lyrics.by/inna/hot.html
  83. http://www.lyrics.by/add.html
                  Земфира - Я полюбила вас

[1]Земфира

   [2]Земфира [3]ФОТОГРАФИИ
   [4]ДИСКОГРАФИЯ
   [5]ИНТЕРВЬЮ
   [6]БИОГРАФИЯ
   [7]ССЫЛКИ
   Альбомы:
   [8]1999, Земфира
   [9]2000, Прости меня, моя любовь
   [10]2002, Четырнадцать недель тишины
   [11]2005, Вендетта
   [12]2007, Спасибо
   Известные песни:
   [13]СПИД
   [14]Созрела
   [15]Прости меня, моя любовь
   [16]Трафик
   [17]Знак бесконечность
   [18]Небомореоблака
   [19]Повесица

   Название песни: Я полюбила вас
   Автор слов: Земфира Рамазанова
   Альбом: [20]"Спасибо" (2007), трек 7
   Продолжительность звучания: 2 мин 45 сек

   Медленно верно газ
   Плыл по уставшей комнате
   Не задевая глаз
   Тех, что вы вряд ли вспомните
   Бился неровно пульс
   Мысли казались голыми
   Из пистолета грусть
   Целилась прямо в голову
   Точки летели вниз
   Матом ругались дворники
   Я выбирала жизнь
   Стоя на подоконнике
   В утренний сонный час
   В час когда все растаяло
   Я полюбила вас
   Марина Цветаева
   Марина


TRANSLATED INTO ENGLISH

Blues
-----

Let's ride through the city
Please, take me
To the bridge, closer
Here I can breathe

So sad because of the moon
Feels like jumping towards her (*)
Let's drink right here and right now

And my police
Will take me and won't choke
Look further, further
Here, never.

Let's ride through the city
Please, take me
To the bridge, closer
Here I can breathe


Pesnya
------

Time is killing me
I am killing time
You and I are still in the game.

We are everything that exists in this world
We are everyone who exist in this world

Proud - yes

Iskala
------
I was looking for you
During long long years
Was looking for you
In dark dark backalleys
In newspapers and movies
Whitin my friends
And the day i found you
I went crazy

Chorus
You, you're just like a dream
Just like in albums
Where I was painting you with gouache

Later went on the night phone calls
More tears, nerves and love
And dates in Poland
Children, but not mine
And old sweethearts

Hochesh
-------
(translated into a seeming imperative
in the end there mightn't be much of a difference).

Please don't die
Or I will have to as well
You, of course, to heaven right away
But I don't think that as well

Want it - sweet oranges
Want it - long tales out loud
Want it - I will blow up all the stars
That are ruining your sleep

Please only live
You must see that I live by you
My enormous love
Will be more than enough for both of us

Want it - sea with sails
Want it - all the newest music
Want it - I will kill all the neighbors
That are ruining your sleep

Want it - sun instead of a lamp
Want it - Alps behind the window
Want it - I will give all the songs
About you I will give all the songs…
Want it - sun instead of a lamp
Want it - Alps behind the window
Want it - I will give all the songs
About you I will give all the songs ...

ANother translation

Do you want? [ Khochesh' (Хочешь?) ]

    Artist: Zemfira (Земфира | Земфира Талгатовна Рамазанова)
    Song: Khochesh' (Хочешь?)
    Translations: Croatian, Czech, English #1, #2, #3, #4, #5, #6, #7, French, German #1, #2, Greek #1, #2, Portuguese, Serbian, Spanish #1, #2, Turkish #1, #2, Ukrainian

English translation
Do you want?
Versions: #1#2#3#4#5#6#7
Do you want?
 
Please, do not die
Or I'll have to do too
Of course, you'll reach the paradise at once
But I'm not sure that I'll reach too
Do you want sweet oranges?
Do you want to hear long stories aloud?
Do you want that I blow up stars
That prevent from sleeping?
 
Please, I wish that you just live
You can see that I live only because of you
My big love
Will be enough for us
Do you want we go in sea under sail?
Do you want the very new musics?
Do you want that I kill neighbors
That prevent from sleeping?
 
Do you want that inspire of lamp is sun?
Do you want that out of window is Alps?
Do you want that I take all songs away
All song about you?
Do you want that inspire of lamp is sun?
Do you want that out of window is Alps?
Do you want that I take all songs away
All song about you?

Prosti menya moya lyubov' 
--------------------------

Sinoptik
--------
Do you want? And I will kill you
I Will only leave your photos
After, I Will buy some glasses with francs
And Nobody Will see the eyes

Painful It won't be - I promise
But you Should send greetings
Call More often
From the sky About the weather

The ones wearing epaulets will look for me
Even the friends will forget the name
All the doors to decent homes will be closed
But what are these slanted gazes to me?
I am outside the law
I am the weatherman.

Painful It won't be - I promise
But you Should send greetings
Call More often
From the sky About the weather

Do you see how it's turning out
April, but sidewalks are skating rinks
If you can't be God
I will be.
Kill, but promise me

Painful It won't be - please try
I will come in the dreams with the rains
Will Call More often
From the sky About the weather

Pripevochka
-----------
He is - your boy
You are - his girl
He is - a cheating liar
But you yourself are not a song*
You left some traces
But he did not understand
What it was
Who it is aside from him

And the knives started flying -
And bunches of accusations
And you got lost in the lies
In the feelings
He is going to kill you, but:
Towards the finale.
Meanwhile, you can breathe
Inhale the spring
Evil
With anyone you want

He is - your boy
You are - his girl
He is - a cheating liar
But and you are not a song*
He mixed it all up,
You lost your cool

You were laughing a long time

And the knives started flying -
And bunches of accusations
And you got lost in the lies
In the feelings towards one another
You will kill him, but:
Towards the finale.
Meanwhile, he can breathe
Inhale the spring
Evil
With anyone you want

And the knives started flying -
And bunches of accusations
And you got lost in the lies
In the feelings
He is definitely going to kill you, but:
Towards the finale.
Meanwhile, you can breathe
Inhale the spring
Evil
With anyone you want

He is - your boy
You are -his girl
He is - a cheating liar
You are - his girl

He is - your boy
You are - his girl
He is - your boy
You are - his girl

ITOGI
-----
I am departing, leaving behind mountains of cigarette stubs
Kilometers’ worth of days, millions of morons
Liters’ worth of blood - given or otherwise lost…

I leave my friends, those who broke themselves in half
On radiowaves, both long and short
Made happy by me, or perhaps hurt by me…

The night torments my swollen eyelids
I remember nothing, nothing of this
My love has remained in the 20th century…

And again it’s night - an arrow tipped with poison
I will never, ever leave you
Just lie down silently next to me…

I am departing, leaving behind reasons to argue
My silly dog, my beloved city
Unsmoked weed, a gigabyte worth of photos…

I leave my dream - maybe someone will want it,
Three notebooks of doubts in my uneven handwriting,
Money in the bank, and many people just like me…

The night torments my swollen eyelids
I remember nothing, nothing of this
My love has remained in the 20th century…

And again it’s night - an arrow tipped with poison
I will never, ever leave you
Just lie down silently next to me ...
